### ISSUE TITLE
plugin nefunguje

### ISSUE THREAD

**Issue by jose1711** [72ka/plugin.video.dmd-czech.playtvak#1]
zrejme kvoli zmene webu. kodi 16.1

```
11:00:46 T:2905144128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'findAll'
                                            Traceback (most recent call last):
                                              File "/home/jose/.kodi/addons/plugin.video.dmd-czech.playtvak/default.py", line 258, in <module>
                                                INDEX(url,page)
                                              File "/home/jose/.kodi/addons/plugin.video.dmd-czech.playtvak/default.py", line 134, in INDEX
                                                items = items.findAll('li')
                                            AttributeError: 'NoneType' object has no attribute 'findAll'
                                            -->End of Python script error report<--
```

**Comment by 72ka** [comment]
Ahoj, zkousel jsem to a jde mi přehrávat vše. Nebyl to jen jednorázový výpadek připojení k internetu? případně prosím a podrobnější popis, v jaké sekci a jaký pořad nešel spustit. Díky

**Comment by jose1711** [comment]
po spusteni a vybere kategorie (napr. porady) sa objavi chybova hlaska. podla tejto to vsak skor vyzera na nekompatibilitu s bs4:

```
10:32:13 T:2947545920   DEBUG: Mode: 6
10:32:13 T:2947545920   DEBUG: URL: http://www.playtvak.cz
10:32:13 T:2947545920   DEBUG: Name: Nejnovější epizody
10:32:13 T:2947545920   DEBUG: Page: 1
10:32:13 T:2947545920   DEBUG: http://www.playtvak.cz
10:32:13 T:2947545920   DEBUG: 1
10:32:13 T:2947545920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: restricted attribute
                                            Traceback (most recent call last):
                                              File "/home/jose/.kodi/addons/plugin.video.dmd-czech.playtvak/default.py", line 240, in <module>
                                                NEW(url,page)
                                              File "/home/jose/.kodi/addons/plugin.video.dmd-czech.playtvak/default.py", line 49, in NEW
                                                doc = bs4.BeautifulSoup(html)
                                              File "/home/jose/.kodi/addons/script.module.dmd-czech.common/lib/bs4/__init__.py", line 196, in __init__
                                                self._feed()
                                              File "/home/jose/.kodi/addons/script.module.dmd-czech.common/lib/bs4/__init__.py", line 210, in _feed
                                                self.builder.feed(self.markup)
                                              File "/home/jose/.kodi/addons/script.module.dmd-czech.common/lib/bs4/builder/_lxml.py", line 225, in feed
                                                self.parser.feed(markup)
                                              File "src/lxml/parser.pxi", line 1194, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:112022)
                                              File "src/lxml/parser.pxi", line 1237, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:111003)
                                              File "src/lxml/parser.pxi", line 827, in lxml.etree._BaseParser._getPushParserContext (src/lxml/lxml.etree.c:106616)
                                              File "src/lxml/parser.pxi", line 844, in lxml.etree._BaseParser._createContext (src/lxml/lxml.etree.c:106827)
                                              File "src/lxml/parsertarget.pxi", line 110, in lxml.etree._TargetParserContext._setTarget (src/lxml/lxml.etree.c:127897)
                                              File "src/lxml/parsertarget.pxi", line 41, in lxml.etree._PythonSaxParserTarget.__cinit__ (src/lxml/lxml.etree.c:126517)
                                              File "/usr/lib/python2.7/inspect.py", line 814, in getargspec
                                                func = func.im_func
                                            RuntimeError: restricted attribute
```

**Comment by 72ka** [comment]
Jo, s bs4 jsem tam zápasil pořád. Zajímavé je, že mě to vše funguje. Také Kodi 16, platformu mám Rpi2 a Win10. Bs4 verzi se podívám až budu mít čas (teď to bohužel opravdu nejde), ale používá to verzi z dmd-czech. Vím že různé verze BS při stejném volání vrací někdy rozdílné výsledky, hrůza..

**Comment by 72ka** [comment]
Zavírám, už je to dlouho a pořád funguje.

**Comment by jose1711** [comment]
este doplnim, ze nakoniec mi pomohlo pridanie 'html5lib' ako druhy argument pri inicializovani BeautifulSoup objektu. preco ale netusim.
