### ISSUE TITLE
Při stahování seznamu videí z Playtvak to skončí chybou

### ISSUE THREAD

**Issue by kozusznik** [72ka/plugin.video.dmd-czech.playtvak#2]
Při stahování seznamu videí z Playtvak to skončí chybou
V logu je pak 
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: restricted attribute
                                            Traceback (most recent call last):
                                              File "~/.kodi/addons/plugin.video.dmd-czech.playtvak/default.py", line 257, in <module>
                                                NEW(url,page)
                                              File "~/.kodi/addons/plugin.video.dmd-czech.playtvak/default.py", line 49, in NEW
                                                doc = bs4.BeautifulSoup(html)
                                              File "~/.kodi/addons/script.module.dmd-czech.common/lib/bs4/__init__.py", line 196, in __init__
                                                self._feed()
                                              File "~/.kodi/addons/script.module.dmd-czech.common/lib/bs4/__init__.py", line 210, in _feed
                                                self.builder.feed(self.markup)
                                              File "~/.kodi/addons/script.module.dmd-czech.common/lib/bs4/builder/_lxml.py", line 225, in feed
                                                self.parser.feed(markup)
                                              File "src/lxml/parser.pxi", line 1194, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:119773)
                                              File "src/lxml/parser.pxi", line 1237, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:118685)
                                              File "src/lxml/parser.pxi", line 827, in lxml.etree._BaseParser._getPushParserContext (src/lxml/lxml.etree.c:113960)
                                              File "src/lxml/parser.pxi", line 844, in lxml.etree._BaseParser._createContext (src/lxml/lxml.etree.c:114186)
                                              File "src/lxml/parsertarget.pxi", line 110, in lxml.etree._TargetParserContext._setTarget (src/lxml/lxml.etree.c:136777)
                                              File "src/lxml/parsertarget.pxi", line 41, in lxml.etree._PythonSaxParserTarget.__cinit__ (src/lxml/lxml.etree.c:135333)
                                              File "/usr/lib/python2.7/inspect.py", line 814, in getargspec
                                                func = func.im_func
                                            RuntimeError: restricted attribute
                                            -->End of Python script error report<--

Pomůže pak zaměnit v plugin.video.dmd-czech.playtvak/default.py
doc = bs4.BeautifulSoup(html) 
   tímto
doc = bs4.BeautifulSoup(html,"html.parser")
nicméně zlobí české názvy pořadů.
Kodi 16.1, Ubuntu 16.04.1
Na jiném počítači se stejným systémem to ale funguje bez úpravy.

**Comment by 72ka** [comment]
Zase nepředvídatelné chování BS. Vzhledem k tomu, že to testuji na Rpi2 a Win10 a Debianu testing, tak to asi nenavodím. Dokážete zjistit verzi BS ve vaší instalaci?

**Comment by kozusznik** [comment]
script.module.dmd-czech.common - 1.5.8 
script.module.beautifulsoup - 3.2.1
script.module.beautifulsoup4 - 4.3.2
ale stejnou chybou končí volání doplňku pro sledujserialy.cz - plugin.video.sledujuserialy.cz
takže to bude určitě někde v chování výše uvedených doplňků. Kodi jsem zkusil přeinstalovat (jak verzi 16.1 tak jsem zkoušel 15) a odebral jsem adresář .kodi, kde si stahuje doplňky a nastavení. Vrtá mi hlavou, proč se to takto chová.

**Comment by 72ka** [comment]
Ahoj, jelikož jsem nepřišel na nic kloudného a chyba se evidentně netýká doplňku samotného, tak to tady uzavírám. Doplněk mi běží i na novém Kodi 17.

**Comment by jose1711** [comment]
poprosim o opatovne otvorenie. kodi 17.5, arch linux, cisty profil. po dohrani najcerstvejsieho playtvaku sa opat objavi vyssie hlasena chyba v logu.

osvedcilo sa mi uprava (na viacerych miestach) v nasledovnom zneni:
```doc = bs4.BeautifulSoup(html) => doc = bs4.BeautifulSoup(html, 'html5lib')```

prosim o opatovne otestovanie stylom:
```
mkdir ~/kodibackup
mv ~/.kodi ~/kodibackup
kodi
konfiguracia repo, stiahnutie playtvaku, spustenie
```
